<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-A34NH13" failures="1" tests="4" name="Pet API Tests" time="8.112" errors="0" timestamp="2025-07-20T22:05:01 IST">
  <testcase classname="tests.PostAddNewPetToStore" name="postPetByValidDetails" time="4.312"/>
  <testcase classname="tests.GetPetByID" name="getPetById" time="1.102"/>
  <testcase classname="tests.StoreTests" name="getPetById" time="1.131"/>
  <testcase classname="tests.DeletesApet" name="getPetById" time="1.133">
    <failure type="java.lang.AssertionError" message="expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [404] but found [200]
at tests.DeletesApet.getPetById(DeletesApet.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- getPetById -->
</testsuite> <!-- Pet API Tests -->
